name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Gradle build test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: tutor
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test-tutor
          MYSQL_PASSWORD: test123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
    - name: Build with Gradle
      run: ./gradlew build
