---
name: Lint Code Base
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-latest
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_FILE_NAME: google_checks.xml
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_XML: false
          VALIDATE_YAML: false
          FILTER_REGEX_INCLUDE: .+\.java|.+\.sql|.+\.yaml|.+\.yml
          JSCPD_CONFIG_FILE: config.jscpd.json
